{//CUADRANTES MENORES 

    if (cuadrante == "A1A1") {

        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/D7G1.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1A2") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1A3") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1A4") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1A5") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1A6") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1A7") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1A8") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1A9") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    }





    if (cuadrante == "A1B1") {

        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/D7G1.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1B2") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1B3") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1B4") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1B5") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1B6") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1B7") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1B8") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1B9") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    }



    if (cuadrante == "A1C1") {

        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/D7G1.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1C2") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1C3") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1C4") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1C5") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1C6") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1C7") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1C8") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1C9") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    }




    if (cuadrante == "A1D1") {

        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/D7G1.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1D2") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1D3") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1D4") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1D5") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1D6") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1D7") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1D8") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1D9") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    }





    if (cuadrante == "A1E1") {

        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/D7G1.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1E2") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1E3") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1E4") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1E5") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1E6") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1E7") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1E8") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1E9") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    }





    if (cuadrante == "A1F1") {

        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/D7G1.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1F2") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1F3") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1F4") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1F5") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1F6") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1F7") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1F8") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1F9") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    }





    if (cuadrante == "A1G1") {

        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/D7G1.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1G2") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1G3") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1G4") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1G5") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1G6") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1G7") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1G8") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1G9") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    }






    if (cuadrante == "A1H1") {

        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/D7G1.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1H2") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1H3") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1H4") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1H5") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1H6") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1H7") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1H8") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1H9") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    }



    if (cuadrante == "A1I1") {

        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/D7G1.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1I2") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1I3") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1I4") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1I5") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1I6") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1I7") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1I8") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    } else if (cuadrante == "A1I9") {
    
        mapaCuadrante = 'url("https://battlerol.net/creador/img/mapas/AGUASINEXPLORADAS.png")'
        consolaMapa.innerHTML = sector.A1
    }

}//FIN CUADRANTES MENORES